### ISSUE TITLE
Request to release the pysciopt folder used in the project

### ISSUE THREAD

**Issue by hongxuanrui1999** [MIRALab-USTC/L2O-HEM#1]
Hello！Your job is excellent, and I want to follow this one. I would like to ask if you have modified the default scip.pyx/pxd file in your project to support it. If so, could you please put pysciopt on Github? Thank you very much！

**Comment by chicwzh** [comment]
Hi, thank you for your question. I have released our modified PySCIPOpt. Please refer to our released code in the updated README.md.

**Comment by hongxuanrui1999** [comment]
Thank you!!!!
